### ISSUE TITLE
Block database

### ISSUE THREAD

**Issue by iamklob** [blockcollider/bcnode#163]
## Description
 
For further clarification see [Fingerprints](https://github.com/blockcollider/bcnode/blob/add-opcodes/src/utils/templates/blockchain_fingerprints.json)

## Tasks

- [ ]     Does this transaction exist in the blockchain?
- [ ]     Does this transaction exist in the connected blockchain?
- [ ]     Does this transaction exist in the connected blockchain block?
- [ ]     Get the graph of the inputs+outputs of the stack
- [ ]     Get the height of graph from input/output to the stackbase of a stack
- [ ]     Get height of transaction tree to coinbase
- [ ]     What is the balance of the Emblems at this address
- [ ]     What is the highest block
- [ ]     What is the highest block of connected blockchain
- [ ]     Get block
- [ ]     Get block of connected blockchain
- [ ]     Get range of block numbers
- [ ]     Get range of block numbers of connected blockchain
- [ ]     Get transaction
- [ ]     Get transaction of connected blockchain
- [ ]     Get transactions of block
- [ ]     Get transactions of block on connected blockchain
- [ ]     Get block which includes transaction of connected blockchain
- [ ]     Get unspent outputs of an address
- [ ]     Add block
- [ ]     Add block of connected blockchain
- [ ]     Remove block
- [ ]     Remove block of connected blockchain
- [ ]     Add transaction
- [ ]     Add transaction to block
- [ ]     Remove transaction
- [ ]     Remove transaction from connected blockchain
